### Script que activa el Firewall de Windows y abre los puertos que est치n actualmente en uso ###
### de todos los servidores definidos en fichero host ###

---
- name: Configurar el firewall en Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Comprobar si el firewall de Windows est치 habilitado
      ansible.windows.win_powershell:
        script: |
          $firewallEnabled = Get-NetFirewallProfile | Where-Object { $_.Enabled -eq 'True' }
          if ($firewallEnabled) {
              Write-Output "El firewall de Windows est치 habilitado."
          } else {
              Write-Output "El firewall de Windows no est치 habilitado. Activando el firewall..."
              Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
          }

    - name: Obtener los puertos de entrada en uso
      ansible.windows.win_powershell:
        script: |
          $ports = Get-NetTCPConnection -State Listen | Select-Object -Unique LocalPort
          $ports

    - name: Crear reglas de firewall para los puertos en uso
      ansible.windows.win_powershell:
        script: |
          $ports = Get-NetTCPConnection -State Listen | Select-Object -Unique LocalPort
          foreach ($port in $ports) {
              $ruleName = "Port_$($port.LocalPort)"
              $existingRule = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue

              if ($existingRule) {
                  Write-Output "La regla para el puerto $($port.LocalPort) ya existe."
              } else {
                  New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -LocalPort $port.LocalPort -Protocol TCP -Action Allow
                  Write-Output "Regla creada para el puerto $($port.LocalPort)."
              }
          }

